version: '3.10'
services:
  api:
    build: .
    container_name: petLivre-api
    command: npm run start:dev
    depends_on:
      - postgresdb
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app

  postgresdb:
    image: postgres:latest
    container_name: petLivre-database
    env_file: ./.env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/backup/files/:/data_backup/
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      postgresdb:
        condition: service_healthy
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data:
