version: '3.10'

services:
  api:
    build: .
    container_name: petLivre-system-api
    command: npm run start:dev
    depends_on:
      - postgresdb
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app/src # ver explicação depois

    # precisa de variáveis relacionadas à aplicação que estão o arquivo development.env
    env_file:
      - ./development.env

  postgresdb:
    image: postgres:latest
    container_name: ${DATABASE_NAME}

    # precisa de configurações específicas do PostgreSQL, as variaveis que estão o arquivo development.env
    env_file:
      - ./development.env

    ports:
      - '5432:5432'
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/backup/files/:/data_backup/
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      postgresdb:
        condition: service_healthy
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data:
